name: backend
description: Backend for Cookkey.
version: 0.0.1
author:
homepage:
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.0.3
  angel_framework: ^2.0.0
  angel_auth: ^2.0.2
  angel_hot: ^2.0.0
  angel_mongo: ^2.0.0
  angel_validate: ^2.0.2
  crypto: ^2.0.0
  
  convenient_bloc:
    path: ../packages/convenient_bloc
  domain:
    path: ../domain

dev_dependencies:
  pedantic: ^1.9.0
  mockito: ^4.1.1