name: domain
description: Cookkey Domain.
version: 0.1.0
author: Karim Mamatkazin
homepage:
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.2.0
  equatable: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  mockito: ^4.1.1
