name: sdk
description: Cookkey SDK.
version: 0.1.0
author: Karim Mamatkazin
homepage:
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.2.0
  equatable: ^1.0.0
  copy_with_extension: ^1.4.0
  angel_validate: ^2.0.2
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0

dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^4.1.1
  copy_with_extension_gen: ^1.4.0
  build_runner: ^1.10.3

